version: 2
project_name: tact

builds:
  - main: ./cmd/tact
    binary: tact
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: Fabio-RibeiroB
    name: tact

